### ISSUE TITLE
bug in dev: student body 0% full time

### ISSUE THREAD

**Issue by hollyallen** [18F/college-choice#1054]
https://federalist.18f.gov/preview/18F/college-choice/dev/school/?196431-Talmudical-Seminary-Oholei-Torah (new code in dev) vs
https://college-choice.18f.gov/school/?196431-Talmudical-Seminary-Oholei-Torah (old code on prod)

0% full time (on dev)
100% full time (on prod)

**Comment by ultrasaurus** [comment]
related issue:  https://github.com/18F/open-data-maker/issues/186

**Comment by ultrasaurus** [comment]
FYI: definitely not an issue with the data, staging with new data matches production
![image](https://cloud.githubusercontent.com/assets/41906/9694675/b2779e66-530f-11e5-986b-f4e031206822.png)


note: full_time is derived from part time.  On dev, part-time is null

**Comment by ultrasaurus** [comment]
I found the cause.  This is data.ayml on production and staging:
```
  student.part_time_share:
    source: PPTUG_EF
    type: float
    description: Share of undergraduate, degree-/certificate-seeking students who
      are part-time
  student.PPTUG_EF2:
    source: PPTUG_EF2
    type: float
    description: Share of undergraduate, degree-/certificate-seeking students who
      are part-time
```

on dev
```
  student.part_time_share:
    source: PPTUG_EF
    type: float
    description: Share of undergraduate, degree-/certificate-seeking students who
      are part-time
  student.PPTUG_EF2:
    source: PPTUG_EF2
    type: float
    description: Share of undergraduate, degree-/certificate-seeking students who
      are part-time
```
