### ISSUE TITLE
As a consumer, on the Individual School page, I'd like to see what programs of study are offered and which are the most popular, so I can get a sense of what I may want to study there.

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#145]
Copying over the task list we're using on other parts of the site (-Michelle):
- [x] Identify the data fields needed to fill in the design.
- [x] Add the corresponding fields to the data API.
- [x] Wire up the data to the HTML.
- [x] Implement design styles in HTML/CSS (MVP). _Done with #145_

![image](https://cloud.githubusercontent.com/assets/12847090/8706760/7c24ccfe-2aff-11e5-9980-d257aa3527a6.png)

this image is also a .pdf, mailed to College Choice mail group.

**Comment by shawnbot** [comment]
@ultrasaurus we're going to need something fancier on the API side for this one. I would expect some JSON like:

```js
{
  "program_percentage": {
    "Accounting": 18,
    "Architecture": 17.5,
    // ...
  }
}
```

Could this be as simple as specifying the field mapping like so, in the proposed YAML structure?

```yaml
fields:
  program_percentage.Accounting:
    source: PCIC01
    type: float
  program_percentage.Architecture:
    source: PCIP04
    type: float
```

Or could we define the `source` of a column as a hash?

```yaml
fields:
  program_percentage:
    type: float
    source:
      Accounting: PCIC01
      Architecture: PCIP04
```

One problem I see is that the data dictionary includes some very length names for its program groups. For instance:

> * Percentage of degrees awarded in 05) AREA, ETHNIC, CULTURAL, GENDER, AND GROUP STUDIES.
> * Percentage of degrees awarded in 43) HOMELAND SECURITY, LAW ENFORCEMENT, FIREFIGHTING AND RELATED PROTECTIVE SERVICES.

@LisaGee, we'll need a way to abbreviate these.
